version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["docker", "dependencies"]
    commit-message:
      prefix: "docker"
