name: "Check Upstream Repository"

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: "<user/repository> of the upstream repository to check for changes"
        required: true
        default: ''
        type: string
      upstream_ref:
        description: "Git reference to compare against (default: main)"
        required: false
        default: 'main'
        type: string

  schedule:
    - cron: '0 * * * *' # Run every hour


jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      has_custom_changes: ${{ steps.discover_custom_changes.outputs.changed_dirs != '' }}
      has_custom_deletions: ${{ steps.discover_custom_changes.outputs.removed_dirs != '' }}
      has_changes: ${{ steps.discover_changes.outputs.changed_dirs != '' }}
      has_deletions: ${{ steps.discover_changes.outputs.removed_dirs != '' }}
      removed_dirs_matrix: ${{ steps.discover_changes.outputs.removed_dirs_matrix }}
      custom_removed_dirs_matrix: ${{ steps.discover_custom_changes.outputs.removed_dirs_matrix }}
      count_removed: ${{ steps.discover_changes.outputs.count_removed }}
      custom_count_removed: ${{ steps.discover_custom_changes.outputs.count_removed }}
      combined_matrix: ${{ steps.discover_changes.outputs.combined_matrix }}
      custom_combined_matrix: ${{ steps.discover_custom_changes.outputs.combined_matrix }}
      count_combined: ${{ steps.discover_changes.outputs.count_combined }}
      custom_count_combined: ${{ steps.discover_custom_changes.outputs.count_combined }}
    steps:
      - name: Generate GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.DYSTOPIANBOT_APP_ID }}
          private-key: ${{ secrets.DYSTOPIANBOT_KEY }}

      - name: Checkout PKGBUILDs repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
          fetch-depth: 0

      - name: Add upstream remote
        id: add_upstream
        uses: DCx7C5/actions/git-add-remote@v1
        with:
          remote_url: 'https://github.com/${{ inputs.upstream_repo || secrets.UPSTREAM_REPO }}'
          remote_name: 'upstream'

      - name: Fetch upstream
        id: fetch_upstream
        uses: DCx7C5/actions/git-fetch@v1
        with:
          remote: 'upstream'
          ref: ${{ inputs.upstream_ref || secrets.UPSTREAM_REF }}

      - name: Discover package changes
        id: discover_changes
        uses: DCx7C5/actions/aur-remote-changes@v1
        with:
          remote_name: 'upstream'
          remote_ref: ${{ inputs.upstream_ref || secrets.UPSTREAM_REF }}
          exclude_paths: |
            .SRCINFO
            .github
            .ci
          exclude_paths_delete: |
            *dystopian*
            *cachy*
          exclude_paths_new: |
            *cachy*
            *dystopian*
          exclude_paths_changed: |
            *cachy*
            *dystopian*

      - name: Discover custom package changes
        id: discover_custom_changes
        uses: DCx7C5/actions/aur-remote-changes@v1
        with:
          remote_name: 'upstream'
          remote_ref: ${{ inputs.upstream_ref || secrets.UPSTREAM_REF }}
          include_only: |
            *dystopian*
            *cachy*
          exclude_paths: |
            .SRCINFO
            .github
            .ci
            

  delete-package:
    needs: discover
    if: needs.discover.outputs.has_removed == 'true'
    strategy:
      fail-fast: false
      max-parallel: ${{ runner.cores }}
      matrix: ${{ fromJson(needs.discover.outputs.removed_dirs_matrix) }}
    uses: ./.github/workflows/delete_package.yml
    secrets: inherit
    with:
      pkg_name: ${{ matrix.dir }}

  sync-package:
    needs:
      - discover
      - delete-package
    if: needs.discover.outputs.has_changes == 'true'
    strategy:
      fail-fast: false
      max-parallel: ${{ runner.cores }}
      matrix: ${{ fromJson(needs.discover.outputs.combined_matrix) }}
    uses: ./.github/workflows/sync_package.yml
    secrets: inherit
    with:
      upstream_repo: ${{ inputs.upstream_repo || secrets.UPSTREAM_REPO }}
      upstream_ref: ${{ inputs.upstream_ref || secrets.UPSTREAM_REF }}
      pkg_name: ${{ matrix.dir }}
      upstream_dir: ${{ matrix.dir }}
      change_type: ${{ matrix.sync_type || 'update' }}

  sync-custom-package:
    needs:
      - discover
      - delete-package
      - sync-package
    if: needs.discover.outputs.has_custom_changes == 'true'
    strategy:
      fail-fast: false
      max-parallel: ${{ runner.cores }}
      matrix: ${{ fromJson(needs.discover.outputs.custom_combined_matrix) }}
    uses: ./.github/workflows/sync_package.yml
    secrets: inherit
    with:
      upstream_repo: ${{ inputs.upstream_repo || secrets.UPSTREAM_REPO }}
      upstream_ref: ${{ inputs.upstream_ref || secrets.UPSTREAM_REF }}
      pkg_name: ${{ matrix.dir }}
      upstream_dir: ${{ matrix.dir }}
      change_type: ${{ matrix.sync_type || 'update' }}

  publish-changes:
    needs:
      - delete-package
      - sync-package
      - sync-custom-package
    uses: ./.github/workflows/publish_package.yml
    secrets: inherit
    with:
      pkg_name: ''